package com.papertrade.bot.api;
import com.papertrade.bot.auth.*; import com.papertrade.bot.db.*; import com.papertrade.bot.strategy.type.MarketStrategyFactory; import jakarta.servlet.http.HttpSession; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import java.math.BigDecimal; import java.util.*;
@RestController @RequestMapping("/api/admin")
public class StrategyAdminController {
 private final StrategyRepository strategies; private final UserRepository users; private final MarketStrategyFactory factory; public StrategyAdminController(StrategyRepository s,UserRepository u,MarketStrategyFactory f){strategies=s;users=u;factory=f;}
 private UserEntity admin(HttpSession s){Object id=s.getAttribute("USER_ID"); Object role=s.getAttribute("ROLE"); if(id==null||!"ADMIN".equals(role)) throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Admin access required"); return users.findById((Long)id).orElseThrow();}
 @GetMapping("/users") public List<Map<String,Object>> users(HttpSession s){admin(s); return users.findAll().stream().map(u->Map.of("id",u.getId(),"name",u.getName(),"email",u.getEmail(),"role",u.getRole().name())).toList();}
 @GetMapping("/strategies") public List<?> all(HttpSession s){admin(s); return strategies.findAll().stream().map(this::dto).toList();}
 @PostMapping("/strategies") public ResponseEntity<?> create(@RequestBody StrategyRequest r,HttpSession s){admin(s); StrategyEntity e=new StrategyEntity(); apply(e,r); strategies.save(e); return ResponseEntity.ok(dto(e));}
 @PutMapping("/strategies/{id}") public Map<String,Object> update(@PathVariable Long id,@RequestBody StrategyRequest r,HttpSession s){admin(s); StrategyEntity e=strategies.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND)); apply(e,r); return dto(strategies.save(e));}
 @PostMapping("/strategies/{id}/assign/{userId}") public ResponseEntity<?> assign(@PathVariable Long id,@PathVariable Long userId,HttpSession s){admin(s); StrategyEntity e=strategies.findById(id).orElseThrow(); UserEntity u=users.findById(userId).orElseThrow(); e.getAssignedUsers().add(u); strategies.save(e); return ResponseEntity.ok(dto(e));}
 @DeleteMapping("/strategies/{id}/assign/{userId}") public ResponseEntity<?> unassign(@PathVariable Long id,@PathVariable Long userId,HttpSession s){admin(s); StrategyEntity e=strategies.findById(id).orElseThrow(); e.getAssignedUsers().removeIf(u->u.getId().equals(userId)); strategies.save(e); return ResponseEntity.ok(dto(e));}
 private void apply(StrategyEntity e,StrategyRequest r){if(r.name()==null||r.name().isBlank()||r.type()==null)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Name and type are required"); factory.get(r.type()); e.setName(r.name().trim());e.setType(r.type());e.setMarket(r.market());e.setSymbol(r.symbol());e.setStartingQuantity(r.startingQuantity());e.setTargetPoints(r.targetPoints());e.setStopLossPoints(r.stopLossPoints());e.setRecoveryPoints(r.recoveryPoints());e.setEnabled(r.enabled()==null||r.enabled());}
 private Map<String,Object> dto(StrategyEntity e){ Map<String,Object> m=new LinkedHashMap<>(); m.put("id",e.getId());m.put("name",e.getName());m.put("type",e.getType().name());m.put("market",e.getMarket());m.put("symbol",e.getSymbol());m.put("startingQuantity",e.getStartingQuantity());m.put("targetPoints",e.getTargetPoints());m.put("stopLossPoints",e.getStopLossPoints());m.put("recoveryPoints",e.getRecoveryPoints());m.put("enabled",e.isEnabled());m.put("engineClass",factory.get(e.getType()).engineClass());m.put("assignedUserIds",e.getAssignedUsers().stream().map(UserEntity::getId).toList());return m;}
 public record StrategyRequest(String name,StrategyType type,String market,String symbol,BigDecimal startingQuantity,BigDecimal targetPoints,BigDecimal stopLossPoints,BigDecimal recoveryPoints,Boolean enabled){}
}
